#! /usr/bin/env python
import sferes

def build(bld):
    osg = not bld.all_envs['default']['NO_OSG']
    #libs = 'EIGEN2 ROBDYN BOOST ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR '
    libs = 'EIGEN3 ROBDYN  BOOST BOOST_TIMER ODE BOOST_SYSTEM BOOST_THREAD BOOST_SERIALIZATION BOOST_FILESYSTEM ROS DYNAMIXEL IMU_RAZOR ROS BAYESIAN_OPTIMIZATION BOOST_CHRONO RT'
    cxxflags = bld.get_env()['CXXFLAGS']
    if osg:
        libs += ' OSG'

    model = bld.new_task_gen('cxx', 'staticlib')
    model.source = 'hexapod.cc '
    model.includes = '. ../../ /usr/include /usr/local/include'
    model.target = 'hexapod'
    model.uselib = libs



    sferes.create_variants(bld,
                           source = 'hexa_supg_hyperneat.cpp',
                           uselib_local = 'sferes2 hexapod',# robot',
                           uselib = libs,
                           target = 'hexa_supg_hyperneat',
                           json = '',
                           variants = ['TEXT','GRAPHIC', 'ORIENTFB TEXT', 'ORIENTFB GRAPHIC', \
                            'OFBV90 ORIENTFB TEXT', 'OFBV90 ORIENTFB GRAPHIC', \
                            'OFBV70 ORIENTFB TEXT', 'OFBV70 ORIENTFB GRAPHIC', \
                            'OFBV50 ORIENTFB TEXT', 'OFBV50 ORIENTFB GRAPHIC', \
                            'OFBV36 ORIENTFB TEXT', 'OFBV36 ORIENTFB GRAPHIC', \
                            'OFBV24 ORIENTFB TEXT', 'OFBV24 ORIENTFB GRAPHIC', \
                            'OFBV18 ORIENTFB TEXT', 'OFBV18 ORIENTFB GRAPHIC', \
                            'OFBV10 ORIENTFB TEXT', 'OFBV10 ORIENTFB GRAPHIC',])
